name: Build and Release Debian Package

on:
  release:
    types: [created]

jobs:
  build_deb:
    strategy:
      matrix:
        ubuntu: ['ubuntu-20.04', 'ubuntu-22.04', 'ubuntu-24.04']
        include:
          - ubuntu: 'ubuntu-20.04'
            codename: 'focal'
          - ubuntu: 'ubuntu-22.04'
            codename: 'jammy'
          - ubuntu: 'ubuntu-24.04'
            codename: 'noble'
    runs-on: ${{ matrix.ubuntu }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - name: Debug Directory Structure
        run: |
          echo "PWD: $(pwd)"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "Contents:"
          ls -la
          echo "Parent contents:"
          ls -la ..

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential dh-make devscripts lintian cmake libhyperscan-dev

      - name: Set version
        run: |
          echo "PACKAGE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          echo "DISTRO_CODENAME=${{ matrix.codename }}" >> $GITHUB_ENV

      - name: Create debian package files
        run: |
          VERSION=${{ env.PACKAGE_VERSION }}
          mkdir -p packages
          mv * packages/ || true
          mv .git* packages/ || true
          mv packages hyperscan-cpp-${VERSION}
          
          # Create orig archive
          tar czf hyperscan-cpp_${VERSION}.orig.tar.gz hyperscan-cpp-${VERSION}
          
          cd hyperscan-cpp-${VERSION}
          
          # Initialize debian directory
          dh_make --library --yes --createorig -p hyperscan-cpp_${VERSION}

          # Continue with your debian file creation...
          # [Previous debian file creation code remains the same]

      - name: Build debian package
        run: |
          VERSION=${{ env.PACKAGE_VERSION }}
          cd hyperscan-cpp-${VERSION}
          dpkg-buildpackage -us -uc
          mkdir -p ../packages
          cp ../libhyperscan-cpp_*.deb ../packages/
          cp ../libhyperscan-cpp-dev_*.deb ../packages/

      - name: Test package installation
        run: |
          sudo dpkg -i packages/libhyperscan-cpp_*.deb
          sudo dpkg -i packages/libhyperscan-cpp-dev_*.deb

      - name: Lint package
        run: |
          lintian packages/*.deb

      - name: Upload packages as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debian-packages-${{ matrix.ubuntu }}
          path: packages/*.deb
          retention-days: 90

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: packages/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}