name: Build and Release Debian Package

on:
  release:
    types: [created]

jobs:
  build_deb:
    strategy:
      matrix:
        ubuntu: ['ubuntu-20.04', 'ubuntu-22.04', 'ubuntu-24.04']
        include:
          - ubuntu: 'ubuntu-20.04'
            codename: 'focal'
          - ubuntu: 'ubuntu-22.04'
            codename: 'jammy'
          - ubuntu: 'ubuntu-24.04'
            codename: 'noble'
    runs-on: ${{ matrix.ubuntu }}

    steps:
      - uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential dh-make devscripts lintian cmake libhyperscan-dev

      - name: Set version
        run: |
          echo "PACKAGE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          echo "DISTRO_CODENAME=${{ matrix.codename }}" >> $GITHUB_ENV

      - name: Create debian package files
        run: |
          # Create orig archive
          tar czf ../hyperscan-cpp_${{ env.PACKAGE_VERSION }}.orig.tar.gz .
          
          # Initialize debian directory
          dh_make --library --yes --createorig

          # Replace default debian files with our versions
          cat << EOF > debian/control
          Source: hyperscan-cpp
          Section: libs
          Priority: optional
          Maintainer: Ludvik Jerabek <ludvikjerabek@users.noreply.github.com>
          Build-Depends: debhelper-compat (= 13), cmake, libhyperscan-dev
          Standards-Version: 4.5.1

          Package: libhyperscan-cpp
          Architecture: any
          Depends: \${shlibs:Depends}, \${misc:Depends}, libhyperscan-dev
          Description: C++ wrapper for Hyperscan library
           A C++ wrapper library for Intel's Hyperscan regular expression matching engine.
           This package contains the shared library.

          Package: libhyperscan-cpp-dev
          Architecture: any
          Section: libdevel
          Depends: libhyperscan-cpp (= \${binary:Version}), \${misc:Depends}, libhyperscan-dev
          Description: Development files for hyperscan-cpp
           A C++ wrapper library for Intel's Hyperscan regular expression matching engine.
           This package contains development files.
          EOF

          # Create changelog with distribution-specific version
          cat << EOF > debian/changelog
          hyperscan-cpp (${{ env.PACKAGE_VERSION }}-1~${{ env.DISTRO_CODENAME }}) ${{ env.DISTRO_CODENAME }}; urgency=medium

            * Release for ${{ matrix.ubuntu }}

           -- Ludvik Jerabek <ludvikjerabek@users.noreply.github.com>  $(date -R)
          EOF

          cat << EOF > debian/rules
          #!/usr/bin/make -f
          %:
          	dh \$@ --buildsystem=cmake

          override_dh_auto_configure:
          	dh_auto_configure -- \
          		-DCMAKE_BUILD_TYPE=Release \
          		-DBUILD_SHARED_LIBS=ON \
          		-DBUILD_STATIC_LIBS=OFF
          EOF

          chmod +x debian/rules

          cat << EOF > debian/libhyperscan-cpp.install
          usr/lib/*/libhyperscan-cpp.so.*
          EOF

          cat << EOF > debian/libhyperscan-cpp-dev.install
          usr/include/hyperscan-cpp/*
          usr/lib/*/libhyperscan-cpp.so
          usr/lib/*/cmake/hyperscan-cpp/*
          EOF

      - name: Build debian package
        run: |
          dpkg-buildpackage -us -uc
          mkdir -p packages
          cp ../libhyperscan-cpp_*.deb packages/
          cp ../libhyperscan-cpp-dev_*.deb packages/

      - name: Test package installation
        run: |
          sudo dpkg -i packages/libhyperscan-cpp_*.deb
          sudo dpkg -i packages/libhyperscan-cpp-dev_*.deb

      - name: Lint package
        run: |
          lintian packages/*.deb

      - name: Upload packages as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debian-packages-${{ matrix.ubuntu }}
          path: packages/*.deb

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: packages/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}